generator:
  class: sfPropelGenerator
  param:
    model_class:           sfGuardGroup
    theme:                 twadmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tw_guard_group
    with_propel_route:     1

    config:
      actions: ~
      fields: ~
      list:
        title: Group list

      filter:
        class: twGuardGroupFormFilter

      edit:
        title: Editing Group "%%name%%"

      new:
        title: New Group
