all:
  tw_admin:
    login:                        false
    logout:                       true
    
    login_route:                  '@tw_guard_signin'
    logout_route:                 '@tw_guard_signout'
    
    module:
      usersadmin:
        label: Użytkownicy
        url:   '@tw_guard_user'
        credentials: [superadmin]

    menu:
      usersadmin:
        categories:
          users:
            label: Użytkownicy
            url:   '@tw_guard_user'
            credentials: [admin]
          permissions:
            label: Uprawnienia
            url:   '@tw_guard_permission'
            credentials: [superadmin]
          groups:
            label: Grupy Uprawnień
            url:   '@tw_guard_group'
            credentials: [superadmin]
    