generator:
  class: twPropelAdminGenerator
  param:
    model_class:           sfGuardUser
    theme:                 twadmin15
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tw_guard_user
    with_propel_route:     1

    config:
      actions: ~
      fields:
        password_again: { label: "Password (again)" }

      list:
        title:   User list
        display: [=username, created_at, last_login]

      filter:
        class: twGuardUserFormFilter
        display: [username, is_active, is_super_admin, sf_guard_user_group_list, sf_guard_user_permission_list]

      form:
        class: sfGuardUserAdminForm
        display:
          "NONE":                   [username, password, password_again]
          "Permissions and groups": [is_active, is_super_admin, sf_guard_user_group_list, sf_guard_user_permission_list]
          #"Profile":                [email, first_name, last_name, birthday, alias, culture]

      edit:
        title: Editing User "%%username%%"

      new:
        title: New User
