generator:
  class: sfPropelGenerator
  param:
    model_class:           sfGuardPermission
    theme:                 twadmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tw_guard_permission
    with_propel_route:     1

    config:
      actions: ~
      fields: ~
      list:
        title: Permission list
        
      filter:
        class: twGuardPermissionFormFilter

      edit:
        title: Editing Permission "%%name%%"

      new:
        title: New Permission
